name: generic-helm-reuse
"on":
    push:
        branches:
            - main
    workflow_dispatch: {}
env:
    ACR_RESOURCE_GROUP: elhays
    AZURE_CONTAINER_REGISTRY: databasecni
    CHART_OVERRIDE_PATH: ./generic/values.yaml
    CHART_OVERRIDES: image.repository=databasecni.azurecr.io/generic-helm-reuse,image.tag=${{github.run_number}}
    CHART_PATH: ./generic
    CLUSTER_NAME: database-cni
    CLUSTER_RESOURCE_GROUP: elhays
    CONTAINER_NAME: generic-helm-reuse
    HELM_ARC_URL: databasecni.azurecr.io
    CONTAINER_NAME_VERSION: ${{github.run_number}}
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                
                
            - name: helm login 
              run: helm registry login ${{ env.HELM_ARC_URL }} --password ${{ secrets.HELM_ACR_SEC }} --username ${{ secrets.HELM_ACR_ACCESS }}
            - name: bump version chart
              run: "sed -i 's/version: [0-9].[0-9].[0-9]/version: '${{ env.CONTAINER_NAME_VERSION }}'/g' generic-helm-reuse/Chart.yaml"
            - name: helm dep build . && helm package 
              run: helm dep build generic-helm-reuse && helm package generic-helm-reuse 
            - name: helm push 
              run: helm push generic-helm-reuse-${{ env.CONTAINER_NAME_VERSION }}.tgz oci://${{ secrets.HELM_ARC_URL }}/helm 
            - name: Build and push image to ${{ secrets.HELM_ARC_URL }}
                
                
                
                
            - name: Build and push image to ACR
              run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_NAME_VERSION }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.ACR_RESOURCE_GROUP }} -f ./Dockerfike ./
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - uses: azure/login@v1.4.3
              name: Azure login
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - uses: azure/use-kubelogin@v1
              name: Set up kubelogin for non-interactive login
              with:
                kubelogin-version: v0.0.25
            - uses: azure/aks-set-context@v3
              name: Get K8s context
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
                use-kubelogin: "true"
            - name: Deploy application
              run: helm upgrade --wait -i -f ${{ env.CHART_OVERRIDE_PATH }} --set ${{ env.CHART_OVERRIDES }} generic-helm-reuse ${{ env.CHART_PATH }}
